services:
  - type: web
    name: mern-app
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      mkdir -p ../backend/public
      cp -r dist/* ../backend/public/
      cd ../backend && npm install
    startCommand: cd backend && NODE_ENV=production node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
