services:
  - type: web
    name: blocklearner-backend
    env: node
    rootDir: .
    buildCommand: |
      # Debug: Show current directory and structure
      echo "Root directory: $PWD"
      ls -la
      
      # Install and build frontend
      echo "Building frontend..."
      cd frontend
      npm install --legacy-peer-deps
      npm run build
      
      # Install and build backend
      echo "Building backend..."
      cd ../backend
      npm install
      
      # Create public directory and copy frontend build
      echo "Creating public directory..."
      mkdir -p public
      
      echo "Copying frontend build files..."
      cp -r ../frontend/dist/* public/
      
      # Verify the copy
      echo "Verifying frontend files..."
      ls -la public/
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://blocklearner-backend.onrender.com
      - key: BACKEND_URL
        value: https://blocklearner-backend.onrender.com
