services:
  - type: web
    name: blocklearner-backend
    env: node
    rootDir: .
    buildCommand: |
      # Debug: Show current directory and structure
      echo "Root directory: $PWD"
      ls -la
      
      # Install dependencies and build
      npm install
      npm run install-all
      npm run build
      
      # Verify the build
      echo "Verifying backend/public directory:"
      ls -la backend/public/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://blocklearner-backend.onrender.com
      - key: BACKEND_URL
        value: https://blocklearner-backend.onrender.com
