services:
  - type: web
    name: blocklearner-backend
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory structure:"
      ls -la
      
      echo "Building frontend..."
      cd frontend
      npm install
      npm run build
      echo "Frontend build complete. Contents of dist:"
      ls -la dist/
      
      echo "Setting up backend..."
      cd ../backend
      npm install
      
      echo "Setting up directory structure..."
      BACKEND_DIR="$PWD"
      PUBLIC_DIR="$BACKEND_DIR/public"
      
      echo "Creating public directory at $PUBLIC_DIR"
      rm -rf "$PUBLIC_DIR"
      mkdir -p "$PUBLIC_DIR"
      
      echo "Copying frontend files..."
      cp -rv "../frontend/dist/"* "$PUBLIC_DIR/"
      
      echo "Final directory structure:"
      ls -la "$PUBLIC_DIR"
      echo "Current path: $PWD"
    startCommand: |
      cd backend
      echo "Starting server from $(pwd)"
      ls -la public/
      NODE_ENV=production node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
