services:
  - type: web
    name: blocklearner-backend
    env: node
    buildCommand: |
      echo "Starting build process..."
      pwd
      echo "Building frontend..."
      cd frontend
      npm install
      npm run build
      echo "Frontend build complete. Contents of dist:"
      ls -la dist/
      cd ..
      echo "Setting up backend..."
      cd backend
      npm install
      echo "Creating public directory..."
      rm -rf public
      mkdir -p public
      echo "Copying frontend files..."
      cp -rv ../frontend/dist/* public/
      echo "Verifying public directory contents:"
      ls -la public/
      pwd
    startCommand: |
      cd backend
      echo "Starting server from $(pwd)"
      NODE_ENV=production node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
