services:
  - type: web
    name: mern-app
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory: $(pwd)"
      ls -la
      
      # Navigate to frontend and build
      echo "Changing to frontend directory..."
      cd ../..
      ls -la
      cd "complete application/frontend"
      echo "Now in frontend directory: $(pwd)"
      ls -la
      
      # Install and build frontend
      echo "Installing frontend dependencies..."
      npm install --force
      echo "Building frontend..."
      CI=false npm run build
      
      # Debug dist directory
      echo "Checking dist directory..."
      ls -la dist/ || echo "dist directory not found!"
      
      # Create and copy to a simpler path
      echo "Setting up build directory..."
      BUILD_DIR="/opt/render/project/src/build"
      rm -rf "$BUILD_DIR"
      mkdir -p "$BUILD_DIR"
      
      echo "Copying build files..."
      cp -r dist/* "$BUILD_DIR/"
      echo "Build directory contents:"
      ls -la "$BUILD_DIR"
      
      # Move to backend and install dependencies
      echo "Installing backend dependencies..."
      cd ../backend
      npm install
      
      echo "Build process complete."
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: BlockLearner
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
