services:
  - type: web
    name: mern-app
    env: node
    buildCommand: |
      echo "Starting build process..."
      pwd
      ls -la
      
      # Build frontend
      echo "Building frontend..."
      cd ../frontend
      echo "Frontend directory:"
      pwd
      ls -la
      
      # Install dependencies and build
      npm install --force
      CI=false npm run build
      
      # Verify build
      echo "Checking build output..."
      ls -la dist/
      
      # Copy to build directory
      echo "Copying build files..."
      mkdir -p /opt/render/project/src/build
      cp -r dist/* /opt/render/project/src/build/
      
      # Verify copy
      echo "Verifying build directory..."
      ls -la /opt/render/project/src/build/
      
      # Install backend dependencies
      echo "Installing backend dependencies..."
      cd ../backend
      npm install
      
      echo "Build process complete"
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: BlockLearner
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
