services:
  - type: web
    name: mern-app
    env: node
    buildCommand: |
      echo "Starting build process..."
      
      # Navigate to frontend and build
      cd "../../complete application/frontend"
      echo "Installing frontend dependencies..."
      npm install --force
      echo "Building frontend..."
      npm run build
      
      # Verify build output
      if [ ! -d "dist" ]; then
        echo "Error: dist directory not created"
        exit 1
      fi
      
      if [ ! -f "dist/index.html" ]; then
        echo "Error: index.html not found in dist"
        exit 1
      fi
      
      echo "Frontend build contents:"
      ls -la dist/
      
      # Create and copy to frontend-dist
      DIST_DIR="/opt/render/project/src/frontend-dist"
      echo "Creating $DIST_DIR"
      mkdir -p "$DIST_DIR"
      
      echo "Copying build files to $DIST_DIR"
      cp -rv dist/* "$DIST_DIR/"
      
      echo "Verifying copied files:"
      ls -la "$DIST_DIR"
      
      # Install backend dependencies
      cd "../backend"
      echo "Installing backend dependencies..."
      npm install
      
      echo "Build process complete."
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: BlockLearner
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
