services:
  - type: web
    name: mern-app
    env: node
    buildCommand: |
      echo "Starting build process..."
      # First, build the frontend
      cd ../frontend
      echo "Installing frontend dependencies..."
      npm install --force
      echo "Building frontend..."
      npm run build
      echo "Frontend build complete. Contents:"
      ls -la dist/
      
      # Now setup backend
      cd ../backend
      echo "Installing backend dependencies..."
      npm install
      echo "Creating build directory..."
      mkdir -p build
      echo "Copying frontend files..."
      cp -r ../frontend/dist/* build/
      echo "Verifying build directory..."
      ls -la build/
      
      echo "Build process complete"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: BlockLearner
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
